lanugage: go
sudo: false

go:
  - "1.10.x"

git:
  depth: 1

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - mkdir -p $GOPATH/src/github.com
  - mv /home/travis/build/callensm $GOPATH/src/github.com

install: true

notifications:
  email: false

before_script:
  - dep ensure

script:
  - make travis