defaults: &defaults
  working_directory: /go/src/github.com/callensm/byte
  docker:
    - image: circleci/golang:1.10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Ensure Dependencies
          command: dep ensure
      - run:
          name: Create Binary
          command: make build
      - run:
          name: Zip Binary with Version
          command: |
            mkdir /tmp/build/
            export BIN_VERSION=`cat VERSION | cut -d'-' -f1`
            zip /tmp/build/byte-$BIN_VERSION.zip /go/bin/byte

      - store_artifacts:
          path: /tmp/build/

  test:
    <<: *defaults
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Run Go Test Files
          command: |
            trap "go-junit-report < ${TEST_RESULTS}/coverage.out > ${TEST_RESULTS}/coverage-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/coverage.out

      - store_artifacts:
          path: /tmp/test-results
          destination: test-output
      
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
