defaults: &defaults
  working_directory: /go/src/github.com/callensm/byte
  docker:
    - image: circleci/golang:1.10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: dep ensure
      - run: make build

      - store_artifacts:
          path: /go/bin/byte

  test:
    <<: *defaults
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Run Go Test Files
          command: |
            trap "go-junit-report < ${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
